version: "3.9"

services:
  back-end:
    build:
      context: ./back-end
    image: softy-pinko-back-end:task5
    expose:
      - "5252"

  front-end:
    build:
      context: ./front-end
    image: softy-pinko-front-end:task5
    expose:
      - "9000"
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
